---
title: "About"
---

## What will you learn?

You will learn how to complete an outbreak analytic task following a practical step-by-step guide to start your own journey.

## Who are these lessons for?

We thought about Lucia, Patricia, and Anya as learner personas in designing the contents of this training:

- [Lucia](https://epiverse-trace.github.io/personas/lucia-outbreaks.html), a Field Epidemiologist in a National Health Agency that uses R for data cleaning, plotting and automated reports.

- [Patricia](https://epiverse-trace.github.io/personas/patricia-discoverer.html), A PhD student learning to use R and analyse Outbreak data for her research project.

- [Anya](https://epiverse-trace.github.io/personas/anya-academica.html), a Professor who needs ready-to-use teaching material for her research and to pass on to students.

<!--

## What design process we follow for these lessons?

- Follow techtogether [design process](https://teachtogether.tech/en/index.html#s:process)
    - Identify the learner persona
        - Their needs are took into account during the whole creation process 
    - Identify the desired data analysis results
        - Define the learning objectives
    - Determine the building blocs
        - Draft a concept map
        - Write the summative assessment
        - Write the formative assessments
    - Write the learning experience
        - Create visuals to explain related concepts
            - vision gathers the most information in the short term memory
        - Use callout blocks for complementary info
            - Refer to existing external or internal materials
                - reconlearn
                - appliedepi
                - graphnet
                - rstudio
                - stackoverflow
                - epiverse-trace github issues

The intention is to capture the decision about why a material is the way it is.

-->

## What design principles we follow for these lessons?

This section aims to capture the decisions about why a material is the way it is.

- A [Tutorial documentation](https://documentation.divio.com/tutorials/) format
    - Easy to consume in a self-paced manner, 
    - Be self-explanatory, 
    - Show common mistakes and misconceptions, and 
    - Write assessment exercises with diagnostic power for those common misconceptions.
- Add links to related [Explanation](https://documentation.divio.com/explanation/) documentation.
- Show the outbreak analytics pipeline approach connecting common policy questions with analysis tasks, data inputs and outputs.
- Order the content to [promote motivation](https://teachtogether.tech/en/index.html#s:motivation-authentic): first the content that requires the less time to master and most useful once mastered. Aligned with the [datasciencebox design principles](https://datasciencebox.org/01-design-principles.html).
- Facilitate the [material maintainability](https://teachtogether.tech/en/index.html#s:process-maintainability). It should be cheaper to update than to replace it.
- Use the lesson folder structure from [The Carpentries workbench](https://github.com/carpentries/workbench-template-rmd), designed accordingly to their [design principles](https://carpentries.org/blog/2020/08/lesson-template-design/#design-principles-for-the-next-iteration-of-the-carpentries-lesson-template).
- Facilitate a multimodal experience:
    - Create visuals to explain related concepts. Vision gathers the most information in the short term memory
    - Create slides or other teacher document (e.g. visual qmd files) to facilitate it's reuse by other instructors for in-person workshops or online trainings.
    - Create interactive videos to create a sense of presence.
    - Add an interactive chatbox for effective one-to-one timely feedback.
    - Use callout blocks for complementary info and refer to existing materials from the epidemiology and data science training community: [reconlearn](https://www.reconlearn.org/), [appliedepi](https://community.appliedepi.org/), [graphnet](https://thegraphcourses.org/), [rstudio](https://posit.cloud/learn/primers), [stackoverflow](https://stackoverflow.com/search?q=epidemiology), github issues and discussions.

## What is not included in this material?

Topics that are out of the scope of these lessons include:

- How to use Git and GitHub to contribute in Open science projects.

- How to create a reproducible analysis project.

- How to build R packages for data analysis tasks.

## Materials you will need

We will use R. For this you will need to use these instructions:

- Install R <https://posit.co/download/rstudio-desktop/>

## How to contribute?

Improvements and additions very welcome, and can be made through the GitHub repository.

## Any questions?

If you need any assistance installing the software or have any other questions about the training, please send an email to [andree.valle-campos\@lshtm.ac.uk](mailto:andree.valle-campos@lshtm.ac.uk){.email}

## References

- [A lesson design process](https://teachtogether.tech/en/index.html#s:process)
